version: '3.5'
services:

#swagger client
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swaggerapi
    hostname: swagger
    # depends_on:
    #   - rest-api
    expose:
      - 8080
    ports:
      - 8029:8080
    environment:
      - API_URL=/swagger.json
    restart: always
    volumes: ["../FIWARE_Cattlechain_Sawtooth_API_Specification/specification.json:/usr/share/nginx/html/swagger.json"]

# sawtooth explorer
  sawtooth-explorer:
    build:
      context: ../FIWARE_Sawtooth_Explorer
    container_name: sawtooth-explorer
    ports:
      - "80:80"